export const messages = [
  { content: "Hii", sender: "User1" },
  { content: "Hello", sender: "User2" },
  { content: "How are you", sender: "User1" },
  { content: "I'm Good", sender: "User2" },
  { content: "What about you?", sender: "User2" },
  { content: "Good", sender: "User1" },
  { content: "Where are you?", sender: "User1" },
  { content: "Hyd", sender: "User2" },
  { content: "Going Home", sender: "User1" },
  { content: "Hii", sender: "User1" },
  { content: "Hello", sender: "User2" },
  { content: "How are you", sender: "User1" },
  { content: "I'm Good", sender: "User2" },
  { content: "What about you?", sender: "User2" },
  { content: "Good", sender: "User1" },
  { content: "Where are you?", sender: "User1" },
  { content: "Hyd", sender: "User2" },
  { content: "Going Home Going Home Going Home Going Home Going Home Going Home Going Home Going Home Going Home ", sender: "User1" },
];
