export const messages = [
  { message: "Hii", sender: "User1" },
  { message: "Hello", sender: "User2" },
  { message: "How are you", sender: "User1" },
  { message: "I'm Good", sender: "User2" },
  { message: "What about you?", sender: "User2" },
  { message: "Good", sender: "User1" },
  { message: "Where are you?", sender: "User1" },
  { message: "Hyd", sender: "User2" },
  { message: "Going Home", sender: "User1" },
  { message: "Hii", sender: "User1" },
  { message: "Hello", sender: "User2" },
  { message: "How are you", sender: "User1" },
  { message: "I'm Good", sender: "User2" },
  { message: "What about you?", sender: "User2" },
  { message: "Good", sender: "User1" },
  { message: "Where are you?", sender: "User1" },
  { message: "Hyd", sender: "User2" },
  { message: "Going Home Going Home Going Home Going Home Going Home Going Home Going Home Going Home Going Home ", sender: "User1" },
];
